apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.nginx.controller_name }}
  namespace: {{ .Values.nginx.controller_name }}
  labels:
    app.kubernetes.io/name: {{ .Values.nginx.controller_name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.nginx.controller_name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.nginx.controller_name }}
    spec:
      serviceAccountName: {{ .Values.nginx.controller_name }}
      containers:
      - name: {{ .Values.nginx.controller_name }}
        image: "k8s.gcr.io/ingress-nginx/controller:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pull_policy }}
        args:
          - /nginx-ingress-controller
          - --ingress-class={{ .Values.nginx.ingress_name }}
          - --watch-ingress-without-class=false
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        ports:
          - containerPort: 80
            name: http
          - containerPort: 443
            name: https
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 10254
          initialDelaySeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /healthz
            port: 10254
          initialDelaySeconds: 10
          timeoutSeconds: 5
