apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nginx.controller_name }}
  namespace: {{ .Values.nginx.controller_name }}
  labels:
    app.kubernetes.io/name: {{ .Values.nginx.controller_name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: 443
      targetPort: 443
      protocol: TCP
      name: https
  selector:
    app.kubernetes.io/name: {{ .Values.nginx.controller_name }}
